<?php
/**
 * Created by PhpStorm.
 * User: 74315
 * Date: 2018/5/23
 * Time: 15:31
 */
namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;

class NewBlogController extends Controller
{
    public function generateshowAction($slug)
    {
        // ...

        // /blog/my-blog-post
        $url = $this->generateUrl(
            'blog_show',
            array('slug' => 'my-blog-post')
        );

        return new Response(
            '<html><body>controllerName: my-blog-post generated by generateshowAction</body></html>'
        );
    }
}