app:
    resource: '@AppBundle/Controller/'
    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /oauth/connect

check_qq:
    path: /oauth/login/check-qq

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

