# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 10
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
            #memory: ~
        oauth:
            id: hwi_oauth.user.provider
        fos_user:
            id: fos_user.user_provider.username



    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: fos_user
                csrf_token_generator: security.csrf.token_manager
            logout: true
            oauth:
                resource_owners:
                    qq: check_qq
                login_path: hwi_oauth_connect
                failure_path: hwi_oauth_connect
                oauth_user_provider:
                    service: hwi_oauth.user.provider

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/news/(new|(\d+\/edit)), roles: IS_AUTHENTICATED_FULLY }